# Site settings
title: QiTASC - The Magic of Testing
email: info@qitasc.com
description: > # this means to ignore newlines until "baseurl:"

  QiTASC is an Austrian company that excels in automated end-to-end testing. Find out how we can help your business achieve a new level of testing with our INTACT® software.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qitasc.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
timezone: Europe/Vienna
encoding: utf-8

defaults:
 -
   scope:
     path: ""
   values:
     layout: "default"


collections:
  jobs:
    output: true
  articles:
      output: true
  tutorials:
      output: true

sass:
  sass_dir: assets/css


# Google Analytics Cide
google_analytics: UA-113548274-2

include: ["articles"]
include: ["tutorials"]
include: ["usecases"]
