# Site settings
title: JasParkety - bright Front End Development
email: hausner.lukas@gmx.at
description: > # this means to ignore newlines until "baseurl:"
  Front End Development

baseurl: "" # the subpath of your site, e.g. /blog/
url: "jas.parkety.github.io"

# Build settings
markdown: kramdown
timezone: Europe/Vienna
encoding: utf-8

defaults:
 -
   scope:
     path: ""
   values:
     layout: "default"

sass:
  sass_dir: css

plugins:
  - jekyll-redirect-from
