- product: INTACT Server
  header: INTACT Server
  text: 'Create, manage and execute automated tests that reflect real-world scenarios, customer experiences and complex relationships with backend systems. The INTACT Server supports real and simulated devices, and provides configurations to ensure that test resources are managed efficiently and that test cases and their results reflect real-life scenarios.'
  subtext: 'While the INTACT Server provides out-of-the-box functionality that covers a large range of potential testing activities, INTACT also facilitates custom scripting, flexible configurations and strong integration capabilities that ensure no details go un-tested.'
  subtext: 'While the INTACT Server provides out-of-the-box functionality that covers a large range of potential testing activities, INTACT also facilitates custom scripting, flexible configurations and strong integration capabilities that ensure no details go un-tested.'
  icon: 'products/Icon_Server.png'

- product: INTACT Studio
  header: INTACT Studio
  text: 'Avoid monotonous, manual tasks and human error with INTACT Studio, an integrated development environment that contains all the productivity boosters that you expect from a professional testing interface.'
  subtext: 'While the INTACT Server provides out-of-the-box functionality that covers a large range of potential testing activities, INTACT also facilitates custom scripting, flexible configurations and strong integration capabilities that ensure no details go un-tested.'
  icon: 'products/Icon_intaQt.png'

- product: INTACT Verification
  header: INTACT Verification
  text: 'Verify hundreds of parameters and metadata within seconds during a test or after data has been collected. With the click of a button, INTACT Verification checks phone, subscriber and event details, internal infrastructure, legal requirements, financial characteristics and more!'
  icon: 'products/Icon_cheQ.png'

- product: INTACT Client
  header: INTACT Client
  text: 'Our command line tool is capable of executing entire INTACT projects in continuous integration (CI) environments such as Jenkins and Team City to maximise levels of automation! INTACT Client also enables the execution of complex test suites via XML configuration.'
  icon: 'products/Icon_intaQt.png'

- product: ConQlude Reporting Service
  header: ConQlude Reporting Service
  text: 'Collect, manage and export INTACT test case project data as well as bug and error tracking without any manual effort. ConQlude Reporting automatically uploads all test reports, logs, media attachments and metadata to a centrally-accessible, secure web interface. This powerful but user-friendly interface ensures that you can remain confident that all test execution details are 100% correct, up-to-date and conform to formats recognized by external project management systems.'
  icon: 'products/Icon_conQlude.png'

- product: sQedule
  header: sQedule
  subheader: The Intelligent Scheduler and Resource Manager
  text: 'Frequently, projects that contain many subscriber and phone-related configurations restrict the amount of phones that can be acquired at random. Sqedule takes care of this by automating device management, executing as many INTACT test cases as possible according to test case properties and available devices.'
  icon: 'products/Icon_sQedule.png'
