Hero:
  mainService: Testing Services
  mainHeader: Testing Services
  mainText: |
      In some cases, such as when customers have a limited time or resources available to do some or all of their testing activities, handing these tasks and responsibilities over to professionals is a cost-effective and reliable solution. QiTASC's testing and professional services allow our partners to focus on critical issues like bug fixing, product development and research without straining their resources on QA activities.
      <br>
      Depending on your requirements, QiTASC's service packages may include:
  enumeration:
    - Managed testing, including implementing test requirements, developing test cases and executing tests
    - Hiring QiTASC test engineers to support your own team
    - Test result analysis
    - Defect management
    - Project management
    - Training in-person or remote
    - Long-term, personalised support via Slack, E-mail and phone
  group: main
  ## imgURL: services/Magier_Testcase_Staple.png


ServiceManaged:
  header: Managed Testing
  text: |
      Managed testing is a great way to see <div class="boldStyleYML">intaQt</div> in action, along with QiTASC's entire range of testing and automation tools, before deciding whether or not to purchase your own licenses. Strong communication between QiTASC and the customer is at the heart of our managed testing services: This helps us transfer knowledge about our software and how it works to the customer while keeping them up-to-date on the status of their test project.
      <br>
       Key features of QiTASC's managed testing may include:
  group: secondary
  enumeration:
    - Developing a risk assessment
    - Defining the test scope from your project's requirements and making sure that all requirements are implemented
    - Converting requirements into test scenarios
    - Writing, executing and analyzing test results
    - Opening defects and tracking bugs
    - Providing and analyzing test reports and metrics

Retest:
  header: Testing and Retesting
  text: |
      Speed, accuracy and reliability are critical to getting your project to the market on time and without any defects.
      QiTASC's testing and retesting services involve contracting our in-house test engineers to execute tests for you.
      <br>
      This is especially useful for businesses in cases such as:
      <br>
  group: secondary
  enumeration:
    - There is a temporary shortage of in-house test engineers
    - Test engineers need to focus on other activities
    - The project needs additional support in executing test themselves, but does not require QiTASC to take full control of the project, like in managed testing

ServiceTraining:
  header: Training
  text: QiTASC offers training packages tailored exactly to your budget as well as your technical and practical needs
  group: secondary

## Sub-category of training:
Classroom:
  header: On-site, Classroom-style Training
  text: Our on-site training services range from half-day sessions that focus on the very specific to two-week comprehensive courses that teach new users how to learn how to confidently use the <div class="boldStyleYML">intaQt Server</div> and <div class="boldStyleYML">intaQt Studio</div>, how these applications integrate with their own test project  and about other QiTASC products such as <div class="boldStyleYML">conQlude</div> and <div class="boldStyleYML">intaQt Client</div>. <br> Comprehensive courses are taught in English by our in-house experts, and are adapted to the specific use cases and requirements of your future projects. This option is strongly recommended for new customers that are purchasing multiple licenses for corporate use. After the training sessions are finished, test engineers are armed with <div class="boldStyleYML">intaQt</div> information and experience that they can share with their colleagues and train themselves. This approach is cost-effective by promoting <div class="boldStyleYML">intaQt</div> knowledge transfer from existing users to new users and hires.
  group: subTraining

## Sub-category of training:
FeatureSpecific:
  header: Feature-specific Training
  text: Often existing customers discover the need develop advanced skills surrounding a few <div class="boldStyleYML">intaQt Server</div> features, or want a quick training session when adding an additional QiTASC product, such as <div class="boldStyleYML">conQlude</div> or <div class="boldStyleYML">intaQt Verification</div> to their workflow. <br> These training sessions may last a few hours, half a day or even 1-2 days, and assume existing <div class="boldStyleYML">intaQt</div> knowledge and prior usage. These training sessions may be conducted on-site or remotely, and are scheduled at times that works best for the customer.
  group: subTraining

SecondaryServices:
    -
      SecondaryService:
        header: Personalized Technical Support
        text: Our team of experts is always available during business hours to help answer technical questions about QiTASC's software or help you troubleshoot errors. Our primary source of technical support is provided via Slack, which ensures a timely response to urgent matters. E-mail, Skype and phone support can also be used when more practical. <br> In order to provide the best technical support possible, we match QiTASC staff with the right technical expertise to understand your test project's details, infrastructure and requirements. This ensures that we can looks at questions and issues from the same perspective as our customers.
        group: secondary
    -
      SecondaryService:
        header: Git Server Hosting
        text: QiTASC offers Git server hosting for customers who want to use version control with their <div class="boldStyleYML">intaQt</div> projects, but don't want to worry about maintenance or space issues. This service package provides users with access to all standard Git hosting functionality, including code reviews and ticket assignment. If at any time you would prefer to handle Git hosting yourself, the service package can be stopped and all artifacts are transfer to the customer.
        group: secondary
    -
      SecondaryService:
        header: Custom Professional Services
        text: |
            Professional services may include a combination of the above service packages, as well as customized services not specified. For example, contracting our in-house engineering team to create hardware to pair with QiTASC's software. This option is popular for business testing Internet of Things applications, which may require additional support in automating devices such as smoke detectors or alarms.
            <br>
            If you do not see a testing service described above, get in touch and let us know what type of specialized assistance you are looking for.
        contact: yes
        group: secondary
